### PR TITLE
Disable query token by default fixes #98

### LINKED ISSUE #98: Make option allowQueryToken false by default.
When this module was created it was just more for allowing token parse by query token than header, but usage and configurability has grown since and should be treated as more secure by default now. As a result, all options for extra areas to parse security tokens should be specifically opt-in so the module is locked down to only header auth by default.

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

**Comment by johnbrett** [comment]
Thanks for the work on this @AdriVanHoudt. I think it might be best to hold on this until there are some other breaking changes, should they pop up. Does that sound ok to you? Happy to proceed if you feel it's important though!

**Comment by AdriVanHoudt** [comment]
Well you can consider the update of joi breaking and I don't see any other issues or features coming up so personally I would do a release.

**Comment by johnbrett** [comment]
Is the update of joi breaking? Or just that we've updated a major version of `joi`?

**Comment by AdriVanHoudt** [comment]
we have updated a major version of joi which did changes to .boolean() and technically it could break when people pass 1 or 'true' (the string) to set `allowQueryToken` for example.
Now I would expect people to not do that but you know ^^

**Comment by johnbrett** [comment]
Thanks for this @AdriVanHoudt - sorry for taking so long to publish!

**Comment by AdriVanHoudt** [comment]
NP! 🚀

**Comment by AdriVanHoudt** [comment]
@johnbrett did you forget to push the commit for the 5.0.0 release? I see npm telling me there is a 5.0.0 release but I don't see anything 5 related in the repo :P

**Comment by johnbrett** [comment]
I 100% forgot to push the commit to the repo @AdriVanHoudt. I don't do as much open source these days, I'm seriously off my game!!

**Pull request merged**
