### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Update dependancies and Code style.

It should maybe be release has a new major version.
(hapi-auth-bearer-token 4.0 for node 4.0 (has 0.10 termination))

### CODE REVIEW

**Comment by johnbrett** [comment]
:+1: Thanks for this also!

**Comment by AdrieanKhisbe** [comment]
you're welcome! :)

(don't forget to bump `"node": ">=0.10.22"` along with the versino for the realease ;) =

**Comment by johnbrett** [comment]
Will do - upgrading dev dependencies as well!

**Comment by AdrieanKhisbe** [comment]
(would be cool also to add a npm badge, cf https://github.com/johnbrett/calibrate/issues/38  :))

**Pull request merged**
