### PR TITLE
Token can be optionally transferred in a cookie, for isomorphic apps

### PR DESCRIPTION
**Pull request by mkawalec**
I think I also overwrote some quotation mark changes, hopefully it will be forgiven :P

### CODE REVIEW

**Comment by mkawalec** [comment]
Oh, tests. If you feel this is a valid direction to evolve, let me know and I'll make the tests pass

**Comment by gr2m** [comment]
Hey @mkawalec, sorry to hijack the PR for a question, but I'm running into the same issue, where we want to build a isomorphic app, but the API is Cookie-less using bearer tokens. Any hints you can give of what you have done to work around the issue?

**Comment by johnbrett** [comment]
Hey @mkawalec @gr2m sincere apologies on slow replies, have a big backlog of stuff to get through! Will try to get to look at this in more detail soon! Have you found a solution in the mean time @mkawalec ?

**Comment by johnbrett** [comment]
Closing due to inactivity, feel free to re-open if you're interested in discussing this more.

**Pull request closed without merging**
