### PR TITLE
Resolve issue #209, doesn't work with new "joi" package.

### PR DESCRIPTION
**Pull request by eric-swann-q2**
As described in issue #209 :

This lib has dependencies on @hapi/joi and @hapi/boom.
The @hapi/joi dependency in particular causes a collision when using the new joi library as joi detects two versions and throws an exception.

Solution: Instead set both of the libraries as peer dependencies for maximum flexibility and reference "joi" as opposed to "@hapi/joi" for future versions.

### CODE REVIEW

**Comment by taina0407** [comment]
@johnbrett any plan for this to merge and release ?

**Comment by wy193777** [comment]
This one is the only dependency currently prevent me update to joi.

**Comment by johnbrett** [comment]
This merge was published as v8.0.0. I considered this a breaking change as it required a change in dependencies. Thanks again @eric-swann-q2. 

@taina0407 @wy193777 please post here if any issues!

**Comment by wy193777** [comment]
Thanks for your immediate response!

**Comment by johnbrett** [comment]
@wy193777 thank @eric-swann-q2, he did all the work here, I just dragged my heels, sorry all!

**Pull request merged**
