### PR TITLE
chore(deps): update deps

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
Free micro markdown fix

### CODE REVIEW

**Comment by johnbrett** [comment]
thanks @AdriVanHoudt 👍

**Comment by AdriVanHoudt** [comment]
@johnbrett np, I was doing an update deps on all my repos and this seemed easy enough, and it causes new builds to not fail due to an old version of lab + new version of node with a new global

**Comment by johnbrett** [comment]
ah I see! That definitely would have took me a while to figure out!

**Comment by AdriVanHoudt** [comment]
yeah it breaks every build on node 8 since lab will say on every build that there is global it doesn't know
I had a bunch of other updates (like new hapi versions) where greenkeeper though it was broken because I hadn't updated lab

**Pull request merged**
